scripts: reformat scripts, and use tabs for indentation
- use tabs for indentation
- some other reformatting and minor linting issues

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

diff --git a/scripts/validate/fileheader b/scripts/validate/fileheader
--- a/scripts/validate/fileheader
+++ b/scripts/validate/fileheader
@@ -14,13 +14,12 @@
 #   See the License for the specific language governing permissions and
 #   limitations under the License.
 
-
 set -eu -o pipefail
 
 if ! command -v ltag; then
-    >&2 echo "ERROR: ltag not found. Install with:"
-    >&2 echo "    go get -u github.com/kunalkushwaha/ltag"
-    exit 1
+	echo >&2 "ERROR: ltag not found. Install with:"
+	echo >&2 "    go get -u github.com/kunalkushwaha/ltag"
+	exit 1
 fi
 
 BASEPATH="${1-}"
